server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy:
        ANT_PATH_MATCHER

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://112.74.185.224:3306/oomall?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: bear
    password: Bear123.

mybatis:
  type-aliases-package: cn.edu.xmu.oomall.payment.model.po
  mapper-locations: classpath*:cn.edu.xmu.oomall.payment.mapper/*.xml
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
