server:
  port: 8081

spring:
  application:
    name: service

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        # 最大连接数量
        max-active: 100
        # 最大空闲连接数量
        max-idle: 100
        # 最小空闲连接数量
        min-idle: 0
        # 连接池最大阻塞等待时间
        max-wait: -1
    # 超时时间，单位：ms
    timeout: 5000

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/bear?serverTimezone=GMT%2B8
    username: bear
    password: 123456

mybatis:
  type-aliases-package: com.bear.service.model.po
  mapper-locations: classpath*:com.bear.service.mapper/*.xml
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true