server:
  port: 8081

spring:
  application:
    name: service

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 0
        max-wait: -1
    timeout: 5000

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://112.74.185.224:3306/bear?serverTimezone=GMT%2B8
    username: bear
    password: Bear123.